package fr.heneria.zombie.core.economy;

/** Stable business reasons used by rewards, purchases and administration. */
public enum TransactionReason {
  STARTING_POINTS,
  ZOMBIE_HIT,
  ZOMBIE_KILL,
  ZOMBIE_ASSIST,
  HEADSHOT_KILL,
  MELEE_KILL,
  BOSS_KILL,
  BARRICADE_REPAIR,
  PLAYER_REVIVE,
  ROUND_COMPLETION,
  OBJECTIVE_REWARD,
  CONTRACT_REWARD,
  POWER_UP_REWARD,
  WALL_WEAPON_PURCHASE,
  WALL_AMMO_PURCHASE,
  MYSTERY_BOX_PURCHASE,
  PACK_A_PUNCH_PURCHASE,
  PERK_PURCHASE,
  DOOR_PURCHASE,
  TRAP_PURCHASE,
  TELEPORTER_PURCHASE,
  ADMIN_GRANT,
  ADMIN_REMOVE,
  ADMIN_SET,
  REFUND,
  CUSTOM
}
