package fr.heneria.bedwars.core.game;

public enum GameOperationCode {
  SUCCESS,
  NOT_FOUND,
  ARENA_NOT_FOUND,
  ARENA_INVALID,
  MAP_NOT_FOUND,
  MAP_INVALID,
  ARENA_OCCUPIED,
  PLAYER_OCCUPIED,
  GAME_FULL,
  INVALID_STATE,
  WORLD_CREATION_FAILED,
  WORLD_DESTRUCTION_FAILED,
  TELEPORT_FAILED,
  INTERNAL_ERROR
}
