config-version: 1

plugin:
  language: fr_FR
  debug: false
  check-updates: false

commands:
  main-command: bedwars
  aliases: [hbw]

security:
  confirm-dangerous-actions: true
  prevent-reload-during-games: true

performance:
  warn-main-thread-task-duration-ms: 50
